# Prometheus 告警规则配置
# 零碳园区数字孪生系统V2.0告警规则

groups:
  # 系统基础设施告警
  - name: infrastructure_alerts
    rules:
      # 服务可用性告警
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "服务 {{ $labels.job }} 不可用"
          description: "服务 {{ $labels.job }} 在实例 {{ $labels.instance }} 上已停止运行超过1分钟"

      # CPU使用率告警
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "CPU使用率过高"
          description: "实例 {{ $labels.instance }} CPU使用率为 {{ $value }}%，超过80%阈值"

      # 内存使用率告警
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "内存使用率过高"
          description: "实例 {{ $labels.instance }} 内存使用率为 {{ $value }}%，超过85%阈值"

      # 磁盘空间告警
      - alert: DiskSpaceHigh
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: critical
          category: storage
        annotations:
          summary: "磁盘空间不足"
          description: "实例 {{ $labels.instance }} 磁盘 {{ $labels.mountpoint }} 使用率为 {{ $value }}%，超过90%阈值"

      # 网络连接数告警
      - alert: HighNetworkConnections
        expr: node_netstat_Tcp_CurrEstab > 1000
        for: 5m
        labels:
          severity: warning
          category: network
        annotations:
          summary: "网络连接数过高"
          description: "实例 {{ $labels.instance }} 当前TCP连接数为 {{ $value }}，超过1000个"

  # 应用性能告警
  - name: application_performance_alerts
    rules:
      # API响应时间告警
      - alert: HighAPIResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 3m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "API响应时间过长"
          description: "95%的API请求响应时间超过500ms，当前为 {{ $value }}s"

      # 错误率告警
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 3m
        labels:
          severity: critical
          category: reliability
        annotations:
          summary: "API错误率过高"
          description: "API错误率为 {{ $value | humanizePercentage }}，超过5%阈值"

      # 请求量异常告警
      - alert: UnusualRequestVolume
        expr: rate(http_requests_total[5m]) > 100 or rate(http_requests_total[5m]) < 1
        for: 5m
        labels:
          severity: warning
          category: traffic
        annotations:
          summary: "请求量异常"
          description: "当前请求量为 {{ $value }} req/s，可能存在异常"

  # 业务指标告警
  - name: business_metrics_alerts
    rules:
      # 能耗监测异常
      - alert: EnergyMonitoringFailure
        expr: increase(energy_monitoring_failures_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "能耗监测异常"
          description: "5分钟内能耗监测失败次数为 {{ $value }}，超过5次"

      # 碳排放计算异常
      - alert: CarbonCalculationError
        expr: increase(carbon_calculation_errors_total[5m]) > 3
        for: 2m
        labels:
          severity: critical
          category: business
        annotations:
          summary: "碳排放计算异常"
          description: "5分钟内碳排放计算错误次数为 {{ $value }}，超过3次"

      # 数据质量异常
      - alert: DataQualityIssue
        expr: data_quality_score < 0.95
        for: 5m
        labels:
          severity: warning
          category: data_quality
        annotations:
          summary: "数据质量下降"
          description: "数据质量评分为 {{ $value }}，低于95%阈值"

      # 实时数据延迟告警
      - alert: RealTimeDataDelay
        expr: time() - real_time_data_last_update_timestamp > 300
        for: 1m
        labels:
          severity: warning
          category: data_freshness
        annotations:
          summary: "实时数据延迟"
          description: "实时数据更新延迟 {{ $value }}秒，超过5分钟"

  # 数据库性能告警
  - name: database_alerts
    rules:
      # 数据库连接数告警
      - alert: HighDatabaseConnections
        expr: db_connections_active / db_connections_max > 0.8
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "数据库连接数过高"
          description: "数据库连接使用率为 {{ $value | humanizePercentage }}，超过80%"

      # 慢查询告警
      - alert: SlowDatabaseQueries
        expr: rate(db_query_duration_seconds{quantile="0.95"}[5m]) > 1
        for: 3m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "数据库查询缓慢"
          description: "95%的数据库查询时间超过1秒"

  # 缓存性能告警
  - name: cache_alerts
    rules:
      # Redis缓存命中率告警
      - alert: LowCacheHitRate
        expr: redis_keyspace_hits_total / (redis_keyspace_hits_total + redis_keyspace_misses_total) < 0.9
        for: 5m
        labels:
          severity: warning
          category: cache
        annotations:
          summary: "缓存命中率过低"
          description: "Redis缓存命中率为 {{ $value | humanizePercentage }}，低于90%"

      # Redis内存使用告警
      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 5m
        labels:
          severity: warning
          category: cache
        annotations:
          summary: "Redis内存使用率过高"
          description: "Redis内存使用率为 {{ $value | humanizePercentage }}，超过80%"

  # 安全告警
  - name: security_alerts
    rules:
      # 异常登录尝试
      - alert: HighFailedLoginAttempts
        expr: rate(failed_login_attempts_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "异常登录尝试"
          description: "5分钟内失败登录尝试次数为 {{ $value }}，可能存在安全威胁"

      # API调用异常
      - alert: SuspiciousAPIActivity
        expr: rate(http_requests_total{status="403"}[5m]) > 5
        for: 3m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "可疑API活动"
          description: "5分钟内403错误次数为 {{ $value }}，可能存在未授权访问"

  # 业务连续性告警
  - name: business_continuity_alerts
    rules:
      # 关键服务不可用
      - alert: CriticalServiceUnavailable
        expr: up{job=~"energy-carbon-center|energy-optimization-center|virtual-power-plant"} == 0
        for: 30s
        labels:
          severity: critical
          category: business_continuity
        annotations:
          summary: "关键业务服务不可用"
          description: "关键服务 {{ $labels.job }} 不可用，影响业务连续性"

      # 数据同步异常
      - alert: DataSyncFailure
        expr: increase(data_sync_failures_total[10m]) > 3
        for: 2m
        labels:
          severity: warning
          category: data_sync
        annotations:
          summary: "数据同步异常"
          description: "10分钟内数据同步失败次数为 {{ $value }}，超过3次"