# 零碳园区数字孪生系统 - 主应用Kubernetes部署配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-system
  namespace: zero-carbon-system
  labels:
    app: energy-system
    component: backend
    version: v2.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: energy-system
  template:
    metadata:
      labels:
        app: energy-system
        component: backend
        version: v2.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/api/metrics"
    spec:
      containers:
      - name: energy-system
        image: zero-carbon/energy-system:v2.0
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: MQTT_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: mqtt-config
              key: broker-url
        - name: PROMETHEUS_ENABLED
          value: "true"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: app-config
          mountPath: /app/config
          readOnly: true
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: app-config
        configMap:
          name: energy-system-config
      - name: logs
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
# Service配置
apiVersion: v1
kind: Service
metadata:
  name: energy-system-service
  namespace: zero-carbon-system
  labels:
    app: energy-system
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3001"
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: energy-system
---
# HorizontalPodAutoscaler配置
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: energy-system-hpa
  namespace: zero-carbon-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: energy-system
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
---
# PodDisruptionBudget配置
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: energy-system-pdb
  namespace: zero-carbon-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: energy-system