/* eslint-disable no-magic-numbers */
/**
 * 数学和基础常量定义
 * 用于替换项目中的魔法数字，提高代码可维护性
 */

// 基础数学常量
export const MATH_CONSTANTS = {
  // 数学相关常量
  PI: Math.PI,
  E: Math.E,
  GOLDEN_RATIO: 1.618033988749895,
  DECIMAL_PLACES: 2, // 小数位数
  
  // 基础数值常量
  ZERO: 0,
  ONE: 1,
  TWO: 2,
  THREE: 3,
  FOUR: 4,
  FIVE: 5,
  SIX: 6,
  SEVEN: 7,
  EIGHT: 8,
  NINE: 9,
  TEN: 10,
  ELEVEN: 11,
  TWELVE: 12,
  THIRTEEN: 13,
  FOURTEEN: 14,
  FIFTEEN: 15,
  SIXTEEN: 16,
  SEVENTEEN: 17,
  EIGHTEEN: 18,
  NINETEEN: 19,
  TWENTY: 20,
  TWENTY_FIVE: 25,
  POINT_ZERO_FOUR: 0.04,
  POINT_ZERO_THREE: 0.03,
  POINT_ZERO_SIX: 0.06,
  TWENTY_ONE: 21,
  TWENTY_TWO: 22,
  TWENTY_THREE: 23,
  TWENTY_FOUR: 24,
  THIRTY: 30,
  THIRTY_ONE: 31,
  THIRTY_TWO: 32,
  THIRTY_THREE: 33,
  THIRTY_FOUR: 34,
  THIRTY_FIVE: 35,
  THIRTY_SIX: 36,
  FORTY: 40,
  FIFTY: 50,
  SIXTY: 60,
  SIXTY_FIVE: 65,
  SEVENTY: 70,
  SEVENTY_TWO: 72,
  SEVENTY_FIVE: 75,
  SEVENTY_EIGHT: 78,
  EIGHTY: 80,
  EIGHTY_FIVE: 85,
  NINETY: 90,
  NINETY_TWO: 92,
  NINETY_FIVE: 95,
  NINETY_EIGHT: 98,
  ONE_HUNDRED: 100,
  EIGHT_HUNDRED: 800,
  TWO_HUNDRED: 200,
  THREE_HUNDRED: 300,
  
  // 时间相关基础数值
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  DAYS_PER_YEAR: 365,
  
  // 时间转换（毫秒）
  MILLISECONDS_PER_SECOND: 1000,
  
  // 存储和数据相关
  BYTES_PER_KB: 1024,
  
  // 百分比相关
  PERCENTAGE_BASE: 100,
  
  // 小数常量
  ZERO_POINT_ZERO_ONE: 0.01,
  ZERO_POINT_ZERO_FIVE: 0.05,
  ZERO_POINT_ONE: 0.1,
  ZERO_POINT_FIFTEEN: 0.15,
  ZERO_POINT_TWO: 0.2,
  ZERO_POINT_FIVE: 0.5,
  ZERO_POINT_SIX: 0.6,
  ZERO_POINT_EIGHT: 0.8,
  POINT_EIGHT: 0.8,
  ZERO_POINT_EIGHTY_FIVE: 0.85,
  POINT_EIGHT_FIVE: 0.85,
  POINT_EIGHT_EIGHT: 0.88,
  POINT_NINE: 0.9,
  POINT_SEVEN: 0.7,
  POINT_SIX: 0.6,
  POINT_SIX_FIVE: 0.65,
  POINT_FIVE: 0.5,
  POINT_TWO_FIVE: 0.25,
  POINT_ONE_NINE: 0.19,
  POINT_ZERO_EIGHT: 0.08,
  POINT_ZERO_SEVEN: 0.07,
  POINT_FOUR: 0.4,
  POINT_THREE: 0.3,
  POINT_ONE: 0.1,
  POINT_ONE_TWO: 1.2,
  ONE_POINT_ZERO: 1.0,
  ONE_POINT_FIVE: 1.5,
  ZERO_POINT_NINE: 0.9,
  ZERO_POINT_NINETY: 0.90,
  ZERO_POINT_NINETY_FIVE: 0.95,
  ZERO_POINT_NINETY_EIGHT: 0.98,
  ZERO_POINT_NINETY_NINE: 0.99,
  POINT_SEVEN_FIVE: 0.75,
  POINT_NINE_FIVE: 0.95,
  POINT_NINE_EIGHT: 0.98,
  
  // 百分比常量
  FIVE_PERCENT: 0.05,
  TEN_PERCENT: 0.1,
  TWENTY_PERCENT: 0.2,
  THIRTY_PERCENT: 0.3,
  FIFTY_PERCENT: 0.5,
  EIGHTY_PERCENT: 0.8,
  NINETY_PERCENT: 0.9,
  
  // 分数常量
  HALF: 0.5,
  ONE_HALF: 0.5,
  ONE_THIRD: 0.33,
  ONE_QUARTER: 0.25,
  
  // 存储和数据相关
  FOUR_HUNDRED: 400,
  FIVE_HUNDRED: 500,
  ONE_THOUSAND: 1000,
  FIFTEEN_HUNDRED: 1500,
  TWO_THOUSAND: 2000,
  THREE_THOUSAND: 3000,
  TWO_THOUSAND_TWO_HUNDRED: 2200,
  POINT_FIVE_SEVEN_ZERO_THREE: 0.5703,
  POINT_TWO: 0.2,
  FIFTEEN_POINT_FIVE: 15.5,
  TWELVE_POINT_THREE: 12.3,
  EIGHT_POINT_SEVEN: 8.7,
  FIVE_POINT_TWO: 5.2,
  NEGATIVE_SIX: -6,
  POINT_ZERO_FIVE: 0.05,
  THREE_THOUSAND_THREE_HUNDRED_SIX: 3306,
  FIVE_THOUSAND: 5000,
  TEN_THOUSAND: 10000,
  FIFTEEN_THOUSAND: 15000,
  TWENTY_THOUSAND: 20000,
  THIRTY_THOUSAND: 30000,
  ONE_MILLION: 1000000,
  SIXTY_SEVEN: 67,
  EIGHTY_EIGHT: 88,
  
  // DataLineageService 相关常量
  
  // 倍数常量
  ONE_POINT_TWO: 1.2,
  
  // 单位转换基数
  UNIT_CONVERSION_BASE: 1000,
  
  // 密码和安全相关
  MIN_PASSWORD_LENGTH: 8,
  CRYPTO_RANDOM_BYTES: 16,
  
  // 能源管理相关常量
  ONE_HUNDRED_TWENTY: 120,
  ONE_HUNDRED_EIGHTY: 180,
  EIGHT_THOUSAND_SEVEN_HUNDRED_SIXTY: 8760,
  
  // 维护管理相关常量
  EIGHT_THOUSAND: 8000,
  
  // NationalIndicatorDashboard 需要的常量
  ONE_POINT_ONE: 1.1,
  NINE_HUNDRED: 900,
  TWO_HUNDRED_FORTY: 240,
  NINE_THOUSAND: 9000,
  
  // 数字常量
  
  // 网络端口常量
  SMTP_SECURE_PORT: 465,
  
  // 颜色常量（十六进制）
  DEFAULT_GRAY_COLOR: 0x808080
};

// 时间间隔常量（基于基础数学常量计算）
export const TIME_INTERVALS = {
  ONE_SECOND_MS: 1000,
  FIVE_SECONDS_MS: 5000,
  TEN_SECONDS_MS: 10000,
  THIRTY_SECONDS_MS: 30000,
  ONE_MINUTE_MS: 60000,
  FIVE_MINUTES_MS: MATH_CONSTANTS.FIVE * MATH_CONSTANTS.SECONDS_PER_MINUTE * MATH_CONSTANTS.MILLISECONDS_PER_SECOND,
  TEN_MINUTES_MS: 600000,
  FIFTEEN_MINUTES_MS: 900000,
  THIRTY_MINUTES_MS: 1800000,
  ONE_HOUR_MS: MATH_CONSTANTS.MINUTES_PER_HOUR * MATH_CONSTANTS.SECONDS_PER_MINUTE * MATH_CONSTANTS.MILLISECONDS_PER_SECOND,
  TWO_HOURS_MS: 7200000,
  SIX_HOURS_MS: 21600000,
  TWELVE_HOURS_MS: 43200000,
  ONE_DAY_MS: MATH_CONSTANTS.HOURS_PER_DAY * MATH_CONSTANTS.MINUTES_PER_HOUR * MATH_CONSTANTS.SECONDS_PER_MINUTE * MATH_CONSTANTS.MILLISECONDS_PER_SECOND,
  ONE_WEEK_MS: 604800000,
  ONE_MONTH_MS: 2592000000,
  ONE_YEAR_MS: MATH_CONSTANTS.DAYS_PER_YEAR * MATH_CONSTANTS.HOURS_PER_DAY * MATH_CONSTANTS.MINUTES_PER_HOUR * MATH_CONSTANTS.SECONDS_PER_MINUTE * MATH_CONSTANTS.MILLISECONDS_PER_SECOND
};

// 能源管理相关常量
export const ENERGY_CONSTANTS = {
  // 能源相关常量
  RENEWABLE_THRESHOLD: 0.3,
  EFFICIENCY_THRESHOLD: 0.8,
  LOAD_BALANCE_THRESHOLD: 0.7,
  OPTIMIZATION_IMPACT: 0.15,
  DEFAULT_MONITORING_INTERVAL: 5 * 60 * 1000, // 5分钟
  OPTIMIZATION_THRESHOLD: 0.1,
  
  // 效率阈值
  EFFICIENCY_THRESHOLD_HIGH: 80,
  EFFICIENCY_THRESHOLD_MEDIUM: 70,
  EFFICIENCY_THRESHOLD_LOW: 50,
  
  // 可再生能源比例阈值
  RENEWABLE_RATIO_THRESHOLD_HIGH: 50,
  RENEWABLE_RATIO_THRESHOLD_LOW: 30,
  
  // 负载因子阈值
  LOAD_FACTOR_THRESHOLD_HIGH: 60,
  LOAD_FACTOR_THRESHOLD_LOW: 50,
  
  // 模拟数据范围
  MOCK_PRODUCTION_MAX: 1000,
  MOCK_CONSUMPTION_MAX: 800,
  MOCK_RENEWABLE_BASE: 60,
  MOCK_RENEWABLE_RANGE: 30,
  MOCK_EFFICIENCY_BASE: 80,
  MOCK_EFFICIENCY_RANGE: 15,
  MOCK_COST_SAVINGS_MAX: 5000,
  MOCK_HOURLY_PRODUCTION_MAX: 100,
  MOCK_HOURLY_CONSUMPTION_MAX: 80,
  MOCK_HOURLY_RENEWABLE_MAX: 60,
  MOCK_DEVICE_CONTRIBUTION_MAX: 100,
  MOCK_DEVICE_EFFICIENCY_BASE: 80,
  MOCK_DEVICE_EFFICIENCY_RANGE: 20,
  MOCK_ENERGY_SAVED_MAX: 50,
  MOCK_COST_SAVED_MAX: 100,
  MOCK_EFFICIENCY_IMPROVED_MAX: 5,
  
  // 时间范围限制
  MAX_HOURLY_DATA_HOURS: 24,
  
  // 碳排放相关常量
  ELECTRICITY_EMISSION_FACTOR: 0.5, // kg CO2e / kWh
  NATURAL_GAS_EMISSION_FACTOR: 0.2, // kg CO2e / kWh
  BASE_ENERGY_USAGE: 500, // kWh
  RANDOM_ENERGY_RANGE: 500 // kWh
};

// 时间范围常量
export const PREVIOUS_TIME_RANGES = {
  ONE_HOUR: '-2 hours',
  SIX_HOURS: '-12 hours',
  ONE_DAY: '-2 days',
  SEVEN_DAYS: '-14 days',
  THIRTY_DAYS: '-60 days',
  NINETY_DAYS: '-180 days',
  ONE_YEAR: '-2 years'
};

// 存储大小常量
export const STORAGE_CONSTANTS = {
  ONE_MB: MATH_CONSTANTS.BYTES_PER_KB * MATH_CONSTANTS.BYTES_PER_KB,
  FILE_SIZE_LIMIT: MATH_CONSTANTS.BYTES_PER_KB * MATH_CONSTANTS.BYTES_PER_KB // 1MB
};

// HTTP状态码常量
export const HTTP_STATUS_CODES = {
  // 成功状态码
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  
  // 重定向状态码
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  NOT_MODIFIED: 304,
  
  // 客户端错误状态码
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  
  // 服务器错误状态码
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504
};

// 数据处理相关常量
export const DATA_PROCESSING_CONSTANTS = {
  // 批处理大小
  BATCH_SIZE_SMALL: 100,
  BATCH_SIZE_MEDIUM: 500,
  BATCH_SIZE_LARGE: 1000,
  BATCH_SIZE_EXTRA_LARGE: 5000,
  
  // 分页相关
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE_SIZE: 1,
  
  // 重试相关
  MAX_RETRY_ATTEMPTS: 3,
  RETRY_DELAY_MS: 1000,
  EXPONENTIAL_BACKOFF_MULTIPLIER: 2,
  
  // 超时设置
  DEFAULT_TIMEOUT_MS: 30000,
  LONG_TIMEOUT_MS: 60000,
  SHORT_TIMEOUT_MS: 5000,
  
  // 缓存相关
  CACHE_TTL_SHORT: 300, // 5分钟
  CACHE_TTL_MEDIUM: 1800, // 30分钟
  CACHE_TTL_LONG: 3600, // 1小时
  CACHE_TTL_EXTRA_LONG: 86400, // 24小时
  
  // 数据验证
  MIN_STRING_LENGTH: 1,
  MAX_STRING_LENGTH: 255,
  MAX_TEXT_LENGTH: 65535,
  
  // 数值范围
  MIN_POSITIVE_NUMBER: 0.0001,
  MAX_SAFE_INTEGER: Number.MAX_SAFE_INTEGER,
  MIN_SAFE_INTEGER: Number.MIN_SAFE_INTEGER
};

// 能源设备相关常量
export const DEVICE_CONSTANTS = {
  // 设备状态
  STATUS_ONLINE: 1,
  STATUS_OFFLINE: 0,
  STATUS_MAINTENANCE: 2,
  STATUS_ERROR: 3,
  
  // 设备类型ID
  TYPE_SOLAR_PANEL: 1,
  TYPE_WIND_TURBINE: 2,
  TYPE_BATTERY: 3,
  TYPE_INVERTER: 4,
  TYPE_METER: 5,
  
  // 设备优先级
  PRIORITY_LOW: 1,
  PRIORITY_MEDIUM: 2,
  PRIORITY_HIGH: 3,
  PRIORITY_CRITICAL: 4,
  
  // 维护间隔（天）
  MAINTENANCE_INTERVAL_DAILY: 1,
  MAINTENANCE_INTERVAL_WEEKLY: 7,
  MAINTENANCE_INTERVAL_MONTHLY: 30,
  MAINTENANCE_INTERVAL_QUARTERLY: 90,
  MAINTENANCE_INTERVAL_YEARLY: 365,
  
  // 设备容量等级
  CAPACITY_SMALL: 10, // kW
  CAPACITY_MEDIUM: 100, // kW
  CAPACITY_LARGE: 1000, // kW
  CAPACITY_EXTRA_LARGE: 10000 // kW
};

// 算法和计算相关常量
export const ALGORITHM_CONSTANTS = {
  // 机器学习相关
  LEARNING_RATE: 0.01,
  EPOCHS: 100,
  BATCH_SIZE: 32,
  VALIDATION_SPLIT: 0.2,
  TEST_SPLIT: 0.1,
  
  // 优化算法参数
  CONVERGENCE_THRESHOLD: 0.001,
  MAX_ITERATIONS: 1000,
  STEP_SIZE: 0.1,
  
  // 统计分析
  CONFIDENCE_LEVEL: 0.95,
  SIGNIFICANCE_LEVEL: 0.05,
  Z_SCORE_THRESHOLD: 2.0,
  
  // 预测模型
  FORECAST_HORIZON_HOURS: 24,
  FORECAST_HORIZON_DAYS: 7,
  FORECAST_HORIZON_MONTHS: 12,
  
  // 异常检测
  ANOMALY_THRESHOLD: 3.0, // 标准差倍数
  OUTLIER_PERCENTILE: 0.95,
  
  // 聚类分析
  MIN_CLUSTER_SIZE: 3,
  MAX_CLUSTER_SIZE: 10,
  CLUSTER_DISTANCE_THRESHOLD: 0.5
};

// 安全和认证相关常量
export const SECURITY_CONSTANTS = {
  // JWT相关
  JWT_EXPIRY_HOURS: 24,
  JWT_REFRESH_EXPIRY_DAYS: 7,
  
  // 密码策略
  MAX_PASSWORD_LENGTH: 128,
  PASSWORD_COMPLEXITY_SCORE: 3,
  
  // 会话管理
  SESSION_TIMEOUT_MINUTES: 30,
  MAX_CONCURRENT_SESSIONS: 5,
  
  // 访问控制
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MINUTES: 15,
  
  // 加密相关
  SALT_ROUNDS: 12,
  ENCRYPTION_KEY_LENGTH: 32,
  IV_LENGTH: 16,
  
  // API限流
  RATE_LIMIT_REQUESTS_PER_MINUTE: 60,
  RATE_LIMIT_REQUESTS_PER_HOUR: 1000,
  RATE_LIMIT_BURST_SIZE: 10
};

// 监控和告警相关常量
export const MONITORING_CONSTANTS = {
  // 告警级别
  ALERT_LEVEL_INFO: 1,
  ALERT_LEVEL_WARNING: 2,
  ALERT_LEVEL_ERROR: 3,
  ALERT_LEVEL_CRITICAL: 4,
  
  // 监控间隔
  MONITOR_INTERVAL_REALTIME: 1000, // 1秒
  MONITOR_INTERVAL_FAST: 5000, // 5秒
  MONITOR_INTERVAL_NORMAL: 30000, // 30秒
  MONITOR_INTERVAL_SLOW: 300000, // 5分钟
  
  // 性能阈值
  CPU_USAGE_WARNING: 70,
  CPU_USAGE_CRITICAL: 90,
  MEMORY_USAGE_WARNING: 80,
  MEMORY_USAGE_CRITICAL: 95,
  DISK_USAGE_WARNING: 85,
  DISK_USAGE_CRITICAL: 95,
  
  // 响应时间阈值（毫秒）
  RESPONSE_TIME_FAST: 100,
  RESPONSE_TIME_NORMAL: 500,
  RESPONSE_TIME_SLOW: 1000,
  RESPONSE_TIME_CRITICAL: 5000,
  
  // 错误率阈值
  ERROR_RATE_WARNING: 0.01, // 1%
  ERROR_RATE_CRITICAL: 0.05, // 5%
  
  // 可用性阈值
  AVAILABILITY_TARGET: 0.999, // 99.9%
  AVAILABILITY_WARNING: 0.99, // 99%
  AVAILABILITY_CRITICAL: 0.95, // 95%
  
  // 质量阈值（百分比）
  QUALITY_THRESHOLD_LOW: 60,
  QUALITY_THRESHOLD_MEDIUM: 75,
  QUALITY_THRESHOLD_HIGH: 85,
  QUALITY_THRESHOLD_VERY_HIGH: 90,
  QUALITY_THRESHOLD_CRITICAL: 95
};

// 碳排放核算相关常量（符合国家标准）
export const CARBON_CONSTANTS = {
  // 缓存超时时间
  CACHE_TIMEOUT: 5 * 60 * 1000, // 5分钟
  
  // 国家标准排放因子（2024年版）
  NATIONAL_EMISSION_FACTORS: {
    // 电力排放因子 (kg CO2/kWh)
    NATIONAL_GRID_ELECTRICITY: 0.5703,
    
    // 区域电网排放因子 (kg CO2/kWh)
    NORTH_CHINA_GRID: 0.8843,
    NORTHEAST_CHINA_GRID: 0.8825,
    EAST_CHINA_GRID: 0.7035,
    CENTRAL_CHINA_GRID: 0.8257,
    NORTHWEST_CHINA_GRID: 0.8922,
    SOUTH_CHINA_GRID: 0.5271,
    
    // 化石燃料排放因子
    NATURAL_GAS: 2.1622, // kg CO2/m³
    COAL: 2.4930, // kg CO2/kg
    DIESEL: 3.0959, // kg CO2/L
    GASOLINE: 2.9251, // kg CO2/L
    HEAVY_OIL: 3.1705, // kg CO2/kg
    LPG: 3.0012, // kg CO2/kg
    
    // 工业过程排放因子
    CEMENT: 0.5273, // kg CO2/kg水泥
    STEEL: 2.07, // kg CO2/kg钢铁
    ALUMINUM: 11.46, // kg CO2/kg铝
    CHEMICAL: 1.5, // kg CO2/kg化工产品（平均值）
    PAPER: 0.9, // kg CO2/kg纸张
    
    // 可再生能源排放因子
    SOLAR: 0.0,
    WIND: 0.0,
    HYDRO: 0.0,
    NUCLEAR: 0.0
  },
  
  // 为测试兼容性添加的排放因子别名
  EMISSION_FACTORS: {
    ELECTRICITY: 0.8325, // kgCO2/kWh
  },
  
  // 工业过程排放因子
  PROCESS_EMISSION_FACTORS: {
  },
  
  // 国家核心指标目标值
  NATIONAL_TARGETS: {
    // 单位能耗碳排放目标值 (吨CO₂/吨标准煤)
    CARBON_INTENSITY_TARGET_MIN: 0.2,
    CARBON_INTENSITY_TARGET_MAX: 0.3,
    
    // 清洁能源消费占比目标值 (%)
    CLEAN_ENERGY_RATIO_TARGET: 90,
    
    // 工业固废综合利用率目标值 (%)
    SOLID_WASTE_UTILIZATION_TARGET: 95,
    
    // 余热/余冷/余压综合利用率目标值 (%)
    WASTE_ENERGY_UTILIZATION_TARGET: 80,
    
    // 工业用水重复利用率目标值 (%)
    WATER_REUSE_TARGET: 90
  },
  
  // 能源折标煤系数
  ENERGY_CONVERSION_FACTORS: {
    // 电力（等价值计算）
    ELECTRICITY_EQUIVALENT: 0.1229, // kgce/kWh
    
    // 化石燃料折标煤系数
    
    // 热力折标煤系数
    HEAT: 0.03412 // kgce/MJ
  },
  
  // 计算精度
  CALCULATION_PRECISION: {
    EMISSION_DECIMAL_PLACES: 4,
    RATIO_DECIMAL_PLACES: 2,
    ENERGY_DECIMAL_PLACES: 3
  },
  
  // 数据质量阈值
  DATA_QUALITY_THRESHOLDS: {
    COMPLETENESS_MIN: 0.95, // 数据完整性最低要求95%
    ACCURACY_MIN: 0.99, // 数据准确性最低要求99%
    TIMELINESS_MAX_DELAY: 60 * 60 * 1000 // 数据时效性最大延迟1小时
  },

  // 数据质量服务相关常量
  DATA_QUALITY_CONSTANTS: {
    // 异常检测相关
    Z_SCORE_SEVERITY_MULTIPLIER: 1.5,
    TREND_DEVIATION_MULTIPLIER: 2,
    PATTERN_THRESHOLD_MULTIPLIER: 2,
    
    // 时间相关（毫秒）
    FUTURE_TIME_TOLERANCE_MS: 300000, // 5分钟未来时间容错
    TWO_MINUTES_MS: 120000,
    SAMPLE_TIME_OFFSET_1MIN: 60000, // 1分钟
    SAMPLE_TIME_OFFSET_2MIN: 120000, // 2分钟
    
    // 质量评分相关
    QUALITY_SCORE_MULTIPLIER: 100,
    DATA_FRESHNESS_SCORE: 0.95,
    ANOMALY_CONFIDENCE_THRESHOLD: 0.9,
    HIGH_QUALITY_SCORE: 0.95,
     METRIC_CHANGE_THRESHOLD: 0.01,
     QUALITY_TARGET_THRESHOLD: 0.9,
    
    // 数据处理相关
    MOCK_TOTAL_RECORDS: 10000,
    VARIANCE_THRESHOLD_MULTIPLIER: 1000,
    NEGATIVE_VARIANCE_THRESHOLD: -1000,
    SMALL_VARIANCE_THRESHOLD: 0.01,
    MAX_HISTORY_RECORDS: 1000,
    
    // 样本数据
    SAMPLE_PRODUCTION_VOLUME: 1000,
     SAMPLE_INDICATOR_VALUE: 0.85,
     SAMPLE_TARGET_VALUE: 0.90,
     MILLION: 1000000,
     HALF_MILLION: 500000,
     BASE_36: 36,
     RANDOM_ID_LENGTH: 9,
     REPORT_ESTIMATE_APPLICATION: 10,
     REPORT_ESTIMATE_ACCEPTANCE: 8,
     REPORT_ESTIMATE_MONITORING: 5,
     REPORT_ESTIMATE_DEFAULT: 5,
     SCORE_GOOD: 80,
     SCORE_WARNING: 60,
     SCORE_CRITICAL: 40,
     SAMPLE_ENTERPRISE_COUNT: 156,
     SAMPLE_EMPLOYEE_COUNT: 12500,
    
    // 时间转换常量
    HOURS_TO_MS: 24 * 60 * 60 * 1000,
    MINUTES_TO_MS: 60 * 1000,
    
    // 趋势分析常量
    TREND_INCREASE_THRESHOLD: 1.2,
    TREND_DECREASE_THRESHOLD: 0.8,
    
    // 查询限制常量
  DEFAULT_QUERY_LIMIT: 100,
  TOP_ITEMS_LIMIT: 10,

  // 告警冷却期常量（10分钟）
  ALERT_COOLDOWN_MS: 10 * 60 * 1000,

  // 错误阈值常量
  ERROR_THRESHOLD_COUNT: 10,
  ERROR_THRESHOLD_TIME_MS: 5 * 60 * 1000,

  // 慢响应阈值常量
  SLOW_RESPONSE_THRESHOLD_MS: 5000,
  SLOW_RESPONSE_COOLDOWN_MS: 60 * 1000,

  // 错误率告警冷却期常量
  ERROR_RATE_COOLDOWN_MS: 5 * 60 * 1000,

  // 错误率阈值常量
  ERROR_RATE_THRESHOLD: 0.05
  }
};

// 导出所有常量的组合对象
export const ALL_CONSTANTS = {
  ...MATH_CONSTANTS,
  ...TIME_INTERVALS,
  ...STORAGE_CONSTANTS,
  ...PREVIOUS_TIME_RANGES,
  ...ENERGY_CONSTANTS,
  ...CARBON_CONSTANTS,
  ...HTTP_STATUS_CODES,
  ...DATA_PROCESSING_CONSTANTS,
  ...DEVICE_CONSTANTS,
  ...ALGORITHM_CONSTANTS,
  ...SECURITY_CONSTANTS,
  ...MONITORING_CONSTANTS
};

export default ALL_CONSTANTS;