/**
 * 碳排放监测模块常量定义
 * 用于替换魔法数字，提高代码可维护性
 */

import { MATH_CONSTANTS, TIME_INTERVALS } from '../../shared/constants/MathConstants.js';

// 时间相关常量
export const TIME_CONSTANTS = {
  MONITORING_INTERVAL: MATH_CONSTANTS.SECONDS_PER_MINUTE * MATH_CONSTANTS.MILLISECONDS_PER_SECOND, // 60秒监控间隔
  FIVE_MINUTES: TIME_INTERVALS.FIVE_MINUTES_MS, // 5分钟
  ONE_HOUR: TIME_INTERVALS.ONE_HOUR_MS, // 1小时
  ONE_DAY: TIME_INTERVALS.ONE_DAY_MS, // 24小时
  ONE_YEAR: TIME_INTERVALS.ONE_YEAR_MS, // 365天
  SECONDS_PER_MINUTE: MATH_CONSTANTS.SECONDS_PER_MINUTE,
  MINUTES_PER_HOUR: MATH_CONSTANTS.MINUTES_PER_HOUR,
  HOURS_PER_DAY: MATH_CONSTANTS.HOURS_PER_DAY,
  DAYS_PER_YEAR: MATH_CONSTANTS.DAYS_PER_YEAR,
  MILLISECONDS_PER_SECOND: MATH_CONSTANTS.MILLISECONDS_PER_SECOND
};

// 百分比和比例常量
export const PERCENTAGE_CONSTANTS = {
  FULL_PERCENTAGE: MATH_CONSTANTS.PERCENTAGE_BASE,
  EFFICIENCY_THRESHOLD: 80,
  REDUCTION_FACTOR: 0.3,
  IMPROVEMENT_FACTOR: 0.2
};

// 数值范围常量
export const RANGE_CONSTANTS = {
  MAX_EMISSION_THRESHOLD: MATH_CONSTANTS.TEN * MATH_CONSTANTS.UNIT_CONVERSION_BASE,
  DAYS_TO_KEEP: 30,
  SUGGESTION_COUNT: MATH_CONSTANTS.FIVE,
  PRIORITY_LEVELS: 20,
  CRYPTO_BYTES: MATH_CONSTANTS.CRYPTO_RANDOM_BYTES,
  PERCENTAGE_THRESHOLD_OFFSET: MATH_CONSTANTS.TEN,
  TIME_RANGE_DIVISOR: MATH_CONSTANTS.FIVE
};

// 单位转换常量
export const CONVERSION_CONSTANTS = {
  KWH_TO_WH: MATH_CONSTANTS.UNIT_CONVERSION_BASE,
  MWH_TO_KWH: MATH_CONSTANTS.UNIT_CONVERSION_BASE,
  GWH_TO_MWH: MATH_CONSTANTS.UNIT_CONVERSION_BASE,
  M3_TO_L: MATH_CONSTANTS.UNIT_CONVERSION_BASE,
  KG_TO_G: MATH_CONSTANTS.UNIT_CONVERSION_BASE,
  KILOGRAMS_TO_GRAMS: MATH_CONSTANTS.UNIT_CONVERSION_BASE,
  METERS_TO_CENTIMETERS: MATH_CONSTANTS.PERCENTAGE_BASE,
  LITERS_TO_MILLILITERS: MATH_CONSTANTS.UNIT_CONVERSION_BASE,
  UNIT_CONVERSION_FACTOR: MATH_CONSTANTS.UNIT_CONVERSION_BASE,
  TIME_SLICE_PRECISION: MATH_CONSTANTS.SIXTEEN,
  PASSWORD_MIN_LENGTH: MATH_CONSTANTS.MIN_PASSWORD_LENGTH,
  FILE_SIZE_LIMIT: MATH_CONSTANTS.BYTES_PER_KB * MATH_CONSTANTS.BYTES_PER_KB // 1MB
};

// 默认减排目标常量
export const REDUCTION_TARGETS = {
  ANNUAL_2024: {
    REDUCTION_PERCENTAGE: 15,
    BASELINE_YEAR: 2023,
    TARGET_YEAR: 2024
  },
  CARBON_NEUTRAL_2030: {
    REDUCTION_PERCENTAGE: 100,
    BASELINE_YEAR: 2023,
    TARGET_YEAR: 2030
  }
};

// 默认碳排放因子
export const DEFAULT_CARBON_FACTORS = {
  ELECTRICITY: 0.5703, // kgCO2e/kWh
  NATURAL_GAS: 2.1622, // kgCO2e/m³
  DIESEL: 2.68, // kgCO2e/L
  GASOLINE: 2.31, // kgCO2e/L
  COAL: 2.42 // kgCO2e/kg
};